# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32, unique=True)),
                ('c_password', models.CharField(max_length=128)),
                ('c_email', models.CharField(max_length=32, unique=True)),
                ('c_is_active', models.BooleanField(default=False)),
                ('c_is_delete', models.BooleanField(default=False)),
                ('c_is_super', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32)),
                ('g_price', models.FloatField(default=1)),
                ('g_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Customer')),
            ],
        ),
    ]
