# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='g_customer',
        ),
        migrations.AddField(
            model_name='goods',
            name='g_num',
            field=models.IntegerField(default=99),
        ),
    ]
