# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-27 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='a_add',
            new_name='a_addr',
        ),
    ]
