# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200627_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='c_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Customer'),
        ),
    ]
