# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200627_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='c_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
    ]
